name: AWS Secrets Manager
description: Read secrets from AWS Secrets Manager
author: https://github.com/seek-oss
requirements:
  - docker
  - jq
configuration:
  properties:
    endpoint-url:
      type: string
    env:
      type: object
    file:
      type: array
    json-to-env:
      type: array
    region:
      type: string
    assume-role-arn:
      type: string
    role-session-name:
      type: string
  required: []
